In [105]:
import sys
import math
from datetime import datetime, timezone
from dyson_pool import DysonPool
from time_utils import TimeManager
import pandas as pd

In [106]:
# Initial pool state
init_eth = 100
init_usdc = 200000
price = init_usdc / init_eth

deposit_dt = datetime(2025, 4, 1, 16, 0, tzinfo=timezone.utc)
withdraw_dt = datetime(2025, 4, 3, 0, 0, tzinfo=timezone.utc)
    
def get_new_pool():
    tm = TimeManager()
    pool = DysonPool(init_eth, init_usdc, basis=0.5, w_factor=1, tm=tm)
    tm.setCurrentTime(deposit_dt)
    return pool, tm

## Test Forward Deposit & Withdraw

In [107]:
# Forward deposit
def process_deposit_withdraw(in0, in1, lock_days):
    pool, tm = get_new_pool()
    deposit_result = pool.deposit(in0, in1, lock_days, price)
    nid, _, _, _, _, _, _, _, _, _ = deposit_result

    print("deposit info:")
    df = pd.DataFrame([deposit_result], columns=['nid', 'note0', 'note1', 'note0_with_prem', 'note1_with_prem', 'prem_ratio', 'due', 'duration_sec', 'q_old', 'q_new'])
    display(df)

    # Withdraw due
    tm.setCurrentTime(withdraw_dt)
    note, withdraw0, withdraw1 = pool.withdraw_due(withdraw_dt, price, nid)

    print("withdraw info:")
    withdraw_df = pd.DataFrame([{'withdraw0': withdraw0, 'withdraw1': withdraw1}])
    display(withdraw_df)

### Test Single Side Deposit

In [108]:
in0, in1, lock_days = 10, 0, 1
process_deposit_withdraw(in0, in1, lock_days)

deposit info:

,nid,note0,note1,note0_with_prem,note1_with_prem,prem_ratio,due,duration_sec,q_old,q_new
0,0,10.0,19058.429278,10.118022,19283.361032,0.011802,20181,115200,0.0,218.279805

withdraw info:

   withdraw0    withdraw1
0    7.58879  4820.319489

### Test Double Side Deposit

In [109]:
in0, in1, lock_days = 1, 2000, 1
process_deposit_withdraw(in0, in1, lock_days)

deposit info:

,nid,note0,note1,note0_with_prem,note1_with_prem,prem_ratio,due,duration_sec,q_old,q_new
0,0,2.0,4000.0,2.024056,4048.111671,0.012028,20181,115200,0.0,44.72136

withdraw info:

   withdraw0    withdraw1
0   1.012028  2024.055836

# Test Withdraw After Rebalance

In [110]:
# Forward deposit
pool, tm = get_new_pool()
in0, in1, lock_days = 10, 0, 1
deposit_result = pool.deposit(in0, in1, lock_days, price)
nid, _, _, _, _, _, _, _, _, _ = deposit_result

pool.rebalance(price)

# Withdraw due
tm.setCurrentTime(withdraw_dt)
note, withdraw0, withdraw1 = pool.withdraw_due(withdraw_dt, price, nid)

print("withdraw info:")
withdraw_df = pd.DataFrame([{'withdraw0': withdraw0, 'withdraw1': withdraw1}])
display(withdraw_df)

withdraw info:

   withdraw0     withdraw1
0   2.465279  14584.926809

# Test Deposit at Midnight

In [111]:
# Forward deposit
pool, tm = get_new_pool()
# 2025-04-02 00:00:00
tm.setCurrentTime(datetime(2025, 4, 2, 0, 0, tzinfo=timezone.utc))
in0, in1, lock_days = 10, 0, 1
deposit_result = pool.deposit(in0, in1, lock_days, price)

print("deposit info:")
df = pd.DataFrame([deposit_result], columns=['nid', 'note0', 'note1', 'note0_with_prem', 'note1_with_prem', 'prem_ratio', 'due', 'duration_sec', 'q_old', 'q_new'])
display(df)

deposit info:

,nid,note0,note1,note0_with_prem,note1_with_prem,prem_ratio,due,duration_sec,q_old,q_new
0,0,10.0,19058.429278,10.10221,19253.225891,0.010221,20181,86400,0.0,218.279805

# Test Multiple Deposits

In [112]:
# Forward deposit
pool, tm = get_new_pool()
in0, in1, lock_days = 10, 0, 1
deposit_result = pool.deposit(in0, in1, lock_days, price)

in0, in1 = 1, 2000
deposit_result2 = pool.deposit(in0, in1, lock_days, price)

print("deposit info:")
df = pd.DataFrame([deposit_result, deposit_result2], columns=['nid', 'note0', 'note1', 'note0_with_prem', 'note1_with_prem', 'prem_ratio', 'due', 'duration_sec', 'q_old', 'q_new'])
display(df)

# Withdraw due
tm.setCurrentTime(withdraw_dt)
nid0 = df.loc[0, "nid"]
nid1 = df.loc[1, "nid"]

note, withdraw0, withdraw1 = pool.withdraw_due(withdraw_dt, price, nid1)

print("nid1 withdraw info:")
withdraw_df = pd.DataFrame([{"withdraw0": withdraw0, "withdraw1": withdraw1}])
display(withdraw_df)

note, withdraw0, withdraw1 = pool.withdraw_due(withdraw_dt, price, nid0)
print("nid0 withdraw info:")
withdraw_df = pd.DataFrame([{"withdraw0": withdraw0, "withdraw1": withdraw1}])
display(withdraw_df)

deposit info:

,nid,note0,note1,note0_with_prem,note1_with_prem,prem_ratio,due,duration_sec,q_old,q_new
0,0,10.000000,19058.429278,10.118022,19283.361032,0.011802,20181,115200,0.000000,218.279805
1,1,2.099955,3818.181818,2.124043,3861.979250,0.011471,20181,115200,218.279805,263.051475

nid1 withdraw info:

   withdraw0    withdraw1
0   1.013213  2019.735153

nid0 withdraw info:

   withdraw0    withdraw1
0   7.587361  4823.042415

## Test Reverse Deposit And Exercise Option

In [113]:
# Before reverse deposit, there sould be enough Q which can be accumulated by forward deposit
in0, in1, lock_days = 1, 2000, 1
pool, tm = get_new_pool()
pool.deposit(in0, in1, lock_days, price)

# Reverse deposit
m, n, lock_days = 1, 200, 1

deposit_result = pool.reverse_deposit(m, n, lock_days, price)
print("Reverse Deposit Info:")
reverse_df = pd.DataFrame([deposit_result], columns=['nid', 'm', 'n', 'strike', 'delta_x', 'delta_y', 'prem_ratio', 'due', 'duration_sec', 'q_old', 'q_new'])
display(reverse_df)

# Exercise option
option_type = "call"  # or 'put'
nid = reverse_df.loc[0, "nid"]
option_type, swap_in, swap_out = pool.exercise_option(nid, option_type)

print(f"Exercised {option_type} option")
print(f"Swap in: {swap_in:.6f}, Swap out: {swap_out:.6f}")

Reverse Deposit Info:

,nid,m,n,strike,delta_x,delta_y,prem_ratio,due,duration_sec,q_old,q_new
0,1,1,200,1982.352941,0.92294,-1777.586866,0.02383,20181,115200,44.72136,20.169201

Exercised call option
Swap in: 1982.352941, Swap out: 1.000000